// Store items for PulsepointStore: digital rewards, branded gear, and gem packs
// XP-based digital items
export const digitalStoreItems = [
  {
    id: 'flashcards_pro',
    name: 'ECG Mastery Flashcards Pack (Pro)',
    description: 'Unlock the full ECG flashcards experience for rapid mastery.',
    type: 'digital',
    cost: 600,
    currency: 'xp',
    image: '/assets/store/flashcards_pro.png',
  },
  {
    id: 'bls_acls_bundle',
    name: 'BLS + ACLS ECG Algorithm Bundle',
    description: 'All key algorithms for BLS and ACLS in one digital bundle.',
    type: 'digital',
    cost: 500,
    currency: 'xp',
    image: '/assets/store/bls_acls_bundle.png',
  },
  {
    id: 'pocket_book',
    name: 'ECGKID Pocket Book (PDF)',
    description: 'A handy PDF reference for ECG interpretation on the go.',
    type: 'digital',
    cost: 800,
    currency: 'xp',
    image: '/assets/store/pocket_book.png',
  },
  {
    id: 'case_scenarios',
    name: '25 ECG Clinical Case Scenarios',
    description: 'Challenge yourself with 25 real-world ECG cases.',
    type: 'digital',
    cost: 400,
    currency: 'xp',
    image: '/assets/store/case_scenarios.png',
  },
  {
    id: 'microlearning_pack',
    name: 'ECG Microlearning Challenge Pack',
    description: 'Bite-sized ECG challenges for daily practice.',
    type: 'digital',
    cost: 300,
    currency: 'xp',
    image: '/assets/store/microlearning_pack.png',
  },
  {
    id: 'axis_guide',
    name: '12-Lead Placement & Axis Guide',
    description: 'Visual guide for 12-lead placement and axis interpretation.',
    type: 'digital',
    cost: 250,
    currency: 'xp',
    image: '/assets/store/axis_guide.png',
  },
  {
    id: 'journal_pages',
    name: 'ECG Journal Pages & Trackers (PDF)',
    description: 'Printable journal and tracker pages for ECG study.',
    type: 'digital',
    cost: 200,
    currency: 'xp',
    image: '/assets/store/journal_pages.png',
  },
  {
    id: 'bonus_quiz',
    name: 'Bonus Quiz (Daily XP Challenge)',
    description: 'Unlock a special bonus quiz for extra XP today!',
    type: 'digital',
    cost: 25,
    currency: 'xp',
    image: '/assets/store/bonus_quiz.png',
  },
];

// Gem-based physical/branded items
export const gemStoreItems = [
  {
    id: 'scrub_top',
    name: 'ECGKID Scrub Top (Unisex)',
    description: 'Official ECGKID branded scrub top, unisex sizing.',
    type: 'physical',
    cost: 600,
    currency: 'gems',
    image: '/assets/store/scrub_top.png',
  },
  {
    id: 'stethoscope_case',
    name: 'Branded Stethoscope Case',
    description: 'Protect your stethoscope in style with ECGKID branding.',
    type: 'physical',
    cost: 450,
    currency: 'gems',
    image: '/assets/store/stethoscope_case.png',
  },
  {
    id: 'poster_set',
    name: 'Clinical ECG Poster Set (2x)',
    description: 'Set of 2 high-quality ECG reference posters.',
    type: 'physical',
    cost: 500,
    currency: 'gems',
    image: '/assets/store/poster_set.png',
  },
  {
    id: 'badge_sticker_pack',
    name: 'ECGKID Badge & Sticker Pack',
    description: 'Fun badge and sticker pack for ECG fans.',
    type: 'physical',
    cost: 300,
    currency: 'gems',
    image: '/assets/store/badge_sticker_pack.png',
  },
  {
    id: 'study_kit',
    name: 'ECGKID Study Kit (Flashcard Deck + Journal)',
    description: 'Complete study kit: flashcards and journal.',
    type: 'physical',
    cost: 700,
    currency: 'gems',
    image: '/assets/store/study_kit.png',
  },
  {
    id: 'water_bottle',
    name: 'Water Bottle (Steel ECG Print)',
    description: 'Steel water bottle with ECG print.',
    type: 'physical',
    cost: 400,
    currency: 'gems',
    image: '/assets/store/water_bottle.png',
  },
];

// Gem packs (for purchase)
export const gemPacks = [
  {
    id: 'starter',
    name: 'Starter Pulsepack',
    gems: 100,
    price: 100,
    bonus: 0,
    currency: 'inr',
  },
  {
    id: 'learner',
    name: 'Learner Pack',
    gems: 250,
    price: 250,
    bonus: 10,
    currency: 'inr',
  },
  {
    id: 'mastery',
    name: 'Mastery Pack',
    gems: 500,
    price: 500,
    bonus: 30,
    currency: 'inr',
  },
  {
    id: 'elite',
    name: 'ECGKID Elite Pack',
    gems: 1000,
    price: 1000,
    bonus: 100,
    currency: 'inr',
  },
  {
    id: 'hero',
    name: 'ECG Hero Bundle',
    gems: 2000,
    price: 2000,
    bonus: 250,
    badge: true,
    currency: 'inr',
  },
];

// Combined export for convenience
export default {
  digitalStoreItems,
  gemStoreItems,
  gemPacks,
};
